export const AUTOCOMPLETE_LOCATION = 'weather-app/Home/AUTOCOMPLETE_LOCATION';
export const AUTOCOMPLETE_LOCATION_SUCCESS = 'weather-app/Home/AUTOCOMPLETE_LOCATION_SUCCESS';
export const AUTOCOMPLETE_LOCATION_ERROR = 'weather-app/Home/AUTOCOMPLETE_LOCATION_ERROR';

export const FIVE_DAY_FORECAST = 'weather-app/Home/FIVE_DAY_FORECAST';
export const FIVE_DAY_FORECAST_SUCCESS = 'weather-app/Home/FIVE_DAY_FORECAST_SUCCESS';
export const FIVE_DAY_FORECAST_ERROR = 'weather-app/Home/FIVE_DAY_FORECAST_ERROR';

export const GEOPOSITION_LOCATION = 'weather-app/Home/GEOPOSITION_LOCATION';
export const GEOPOSITION_LOCATION_SUCCESS = 'weather-app/Home/GEOPOSITION_LOCATION_SUCCESS';
export const GEOPOSITION_LOCATION_ERROR = 'weather-app/Home/GEOPOSITION_LOCATION_ERROR';
